"""Package-registry / SaaS token rules (Tier 2): npm, PyPI, OpenAI, SendGrid, Twilio."""

from secretsieve.models.rule import compile_rule

RULES = [
    compile_rule(
        rule_id="SS-NPM-001",
        name="npm Access Token",
        provider="npm",
        category="api_token",
        severity="HIGH",
        pattern=r"npm_[A-Za-z0-9]{36,80}",
        base_confidence=88,
        entropy_profile="base64",
        keywords=("npm", "token"),
        description="npm classic access token.",
        remediation="Revoke at npmjs.com access-tokens and rotate.",
        fp_notes="Fixed npm_ prefix; high precision.",
    ),
    compile_rule(
        rule_id="SS-PYPI-001",
        name="PyPI API Token",
        provider="pypi",
        category="api_token",
        severity="HIGH",
        pattern=r"pypi-[A-Za-z0-9_\-]{30,100}",
        base_confidence=88,
        entropy_profile="base64",
        keywords=("pypi", "token"),
        description="PyPI API token (pypi- prefix).",
        remediation="Delete the token on PyPI and rotate; scope to one project.",
        fp_notes="Fixed pypi- prefix; high precision.",
    ),
    compile_rule(
        rule_id="SS-OPENAI-001",
        name="OpenAI API Key",
        provider="openai",
        category="api_token",
        severity="HIGH",
        pattern=r"sk-[A-Za-z0-9]{32,80}",
        base_confidence=88,
        validator="openai_key",
        entropy_profile="base64",
        keywords=("openai", "sk-", "api_key"),
        description="OpenAI API key (sk- + 32+ chars; disambiguated from Stripe sk_live/sk_test).",
        remediation="Revoke in the OpenAI dashboard and rotate; set usage limits.",
        fp_notes="Stripe sk_live_/sk_test_ shapes are routed to SS-STRIPE-001, never here.",
    ),
    compile_rule(
        rule_id="SS-SENDGRID-001",
        name="SendGrid API Key",
        provider="sendgrid",
        category="api_token",
        severity="HIGH",
        pattern=r"SG\.[A-Za-z0-9_\-]{22}\.[A-Za-z0-9_\-]{30,60}",
        base_confidence=88,
        entropy_profile="base64",
        keywords=("sendgrid", "SG."),
        description="SendGrid v3 API key (SG.22.43 shape).",
        remediation="Delete the key in SendGrid settings and rotate.",
        fp_notes="Rigid SG. shape; high precision.",
    ),
    compile_rule(
        rule_id="SS-TWILIO-001",
        name="Twilio API Key",
        provider="twilio",
        category="api_token",
        severity="HIGH",
        pattern=r"SK[0-9a-fA-F]{32}",
        base_confidence=85,
        context_required=True,
        entropy_profile="hex",
        keywords=("twilio", "SK", "account_sid", "auth_token"),
        description="Twilio API key (SK + 32 hex chars); requires Twilio context.",
        remediation="Close the key in the Twilio console and rotate the auth token.",
        fp_notes="Hex-heavy shape overlaps digests, so Twilio/account context is required.",
    ),
]
